export const LOGIN_ERROR_TYPES = {
    INVALID_USERNAME: 'INVALID_USERNAME',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    UNVERIFIED_ACCOUNT: 'UNVERIFIED_ACCOUNT',
    BLOCKED_ACCOUNT: 'BLOCKED_ACCOUNT'
}

export const PRODUCT_ERROR_TYPES = {
    CAR_MAKE_NOT_FOUND: 'CAR_MAKE_NOT_FOUND',
    CAR_MODEL_NOT_FOUND: 'CAR_MODEL_NOT_FOUND',
    MAXIMUM_8_MEDIAS_ALLOWED: 'MAXIMUM_8_MEDIAS_ALLOWED',
    MAXIMUM_1_MEDIAMAIN_ALLOWED: 'MAXIMUM_1_MEDIAMAIN_ALLOWED',
    MAXIMUM_FILE_SIZE_EXCEEDED: 'MAXIMUM_FILE_SIZE_EXCEEDED',
    FILE_EXTENSION_NOT_FOUND: 'FILE_EXTENSION_NOT_FOUND',
    FILE_EXTENSION_NOT_SUPPORTED: 'FILE_EXTENSION_NOT_SUPPORTED',
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
}