export const GENERAL_CONSTS = {
    GET_STATIC_TEXTS: "GET_STATIC_TEXTS",
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_FILTERS: "GET_FILTERS",

    GET_CAR_MAKES:"GET_CAR_MAKES",
    GET_CAR_MODELS:"GET_CAR_MODELS",
    CLEAR_CAR_MODELS:"CLEAR_CAR_MODELS",

    GET_LANGUAGES: "GET_LANGUAGES",
    GET_MAIN_SLIDER: "GET_MAIN_SLIDER",
    SET_SELECTED_LANGUAGE: "SET_SELECTED_LANGUAGE",
    SET_FAQ_LIST: "SET_FAQ_LIST",
    SET_CONTACT: "SET_CONTACT",
    TOGGLE_BROWSER_TAB_VISIBILITY: "TOGGLE_BROWSER_TAB_VISIBILITY",
};
