export const MESSAGE_CONSTS = {
    GET_MESSAGES_BY_ROOM_ID: "GET_MESSAGES_BY_ROOM_ID",

    CLEAR_ACTIVE_ROOM_LIST: "CLEAR_ACTIVE_ROOM_LIST",
    GET_ROOMS: "GET_ROOMS",
    GET_ROOM_BY_USER_ID: "GET_ROOM_BY_USER_ID",
    DELETE_ROOM: "DELETE_ROOM",
    BLOCK_ROOM: "BLOCK_ROOM",
    UNBLOCK_ROOM: "UNBLOCK_ROOM",
};
