export const PRODUCT_CONSTS = {
    GET_SEARCHED_PRODUCTS: 'GET_SEARCHED_PRODUCTS',
    CLEAR_SEARCHED_PRODUCTS: "CLEAR_SEARCHED_PRODUCTS",

    GET_SINGLE_PRODUCT: 'GET_SINGLE_PRODUCT',
    CLEAR_SINGLE_PRODUCT: 'CLEAR_SINGLE_PRODUCT',

    GET_PRODUCTS_BY_USER_ID: 'GET_PRODUCTS_BY_USER_ID',
    CLEAR_PRODUCTS_BY_USER_ID: 'CLEAR_PRODUCTS_BY_USER_ID',

    GET_PRODUCT_SECTIONS: 'GET_PRODUCT_SECTIONS',
    GET_HOMEPAGE_SECTIONS: 'GET_HOMEPAGE_SECTIONS',

    TOGGLE_PRODUCT_LIKE: 'TOGGLE_PRODUCT_LIKE',

    BLOCK_PRODUCT: 'BLOCK_PRODUCT',
    UN_BLOCK_PRODUCT: 'UN_BLOCK_PRODUCT',

    GET_SUGGESTIONS:'GET_SUGGESTIONS',

    //User Own products
    ADD_PRODUCT: "ADD_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    GET_FAVORITE_PRODUCTS:'GET_FAVORITE_PRODUCTS',
    GET_BLOCKED_PRODUCTS:'GET_BLOCKED_PRODUCTS',
    GET_OWN_PRODUCTS: 'GET_OWN_PRODUCTS',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
};
