export const UTIL_CONSTS = {
    START_LOADING: "START_LOADING",
    END_LOADING: "END_LOADING",
    TOGGLE_NOTIFICATION_ROW: "TOGGLE_NOTIFICATION_ROW",

    SET_META_DATA: "SET_META_DATA",
    CLEAR_META_DATA: "CLEAR_META_DATA",
};
